services:
  qa-demo-service:
    container_name: qa-demo-service
    depends_on:
      - qa-demo-mongo
      - qa-demo-kafka
    environment:
      MONGODB_URL: mongodb://qa-demo-mongo:27017/demo_db
      KAFKA_SERVER: qa-demo-kafka:9092
      EXTERNAL_SERVICE: http://qa-demo-wiremock:8080
    build:
      context: ../../
      dockerfile: docker/Dockerfile/demo-service
    ports:
      - "8080:8080"
    networks:
      - qa-demo-app
      - qa-demo-e2e

  qa-demo-interface:
    container_name: qa-demo-interface
    build:
      context: ../../
      dockerfile: docker/Dockerfile/demo-interface
    ports:
      - "5173:5173"
    environment:
      - VITE_BE_PROXY_TARGET=http://qa-demo-service:8080
    networks:
      - qa-demo-e2e

  qa-demo-mongo:
    image: mongo:4.4
    container_name: qa-demo-mongo
    expose:
      - 27018
    ports:
      - "27018:27017"
    command: [ "--replSet", "rs0", "--bind_ip_all", "--setParameter", "enableTestCommands=1" ]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 60s
      start_period: 60s
    volumes:
      - mongo-volume:/data/db
      - ./scripts/mongo:/docker-entrypoint-initdb.d/
    networks:
      - qa-demo-app

  qa-demo-kafka:
    image: apache/kafka:3.7.1
    container_name: qa-demo-kafka
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://qa-demo-kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@qa-demo-kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - '9094:9094'
    networks:
      - qa-demo-app

  qa-demo-wiremock:
    image: wiremock/wiremock:3.9.2
    container_name: qa-demo-wiremock
    ports:
      - '8085:8080'
    volumes:
      - ./mappings:/home/wiremock/mappings
    networks:
      - qa-demo-app
      - qa-demo-e2e

volumes:
  mongo-volume:

networks:
  qa-demo-app:
  qa-demo-e2e:
    external: true
