version: '3.7'

services:
  qa-demo-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile-demo-service
    container_name: qa-demo-service
    ports:
      - "8080:8080"
  qa-demo-interface:
    build:
      context: ../
      dockerfile: docker/Dockerfile-demo-interface
    container_name: qa-demo-interface
    ports:
      - "3000:3000"
