FROM maven:3.8.3-openjdk-17
COPY demo-service/src /src
COPY demo-service/pom.xml /
RUN mvn -Djdk.lang.Process.launchMechanism=vfork -Dtests.skip=true package
CMD java -jar /target/demo-service.jar --spring.data.mongodb.uri=$MONGODB_URL --kafka.bootstrap-servers=$KAFKA_SERVER --external.service.url=$EXTERNAL_SERVICE
