services:
  qa-demo-service:
    container_name: qa-demo-service
    build:
      args:
        MONGODB_URL_ARG: mongodb://172.17.0.1:27018/demo_db
      context: ../
      dockerfile: docker/Dockerfile-demo-service
    ports:
      - "8080:8080"
    
  qa-demo-interface:
    container_name: qa-demo-interface
    build:
      args:
        BE_API_ARG: http://http://172.17.0.1:8080/v1
      context: ../
      dockerfile: docker/Dockerfile-demo-interface
    ports:
      - "3000:3000"
