# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.3'

gem 'allure-rspec', '~> 2.24'
gem 'capybara', '~> 3.40'
gem 'dotenv', '~> 3.1'
gem 'faraday', '~> 2.12'
gem 'puffing-billy', '~> 4.0'
gem 'rake', '~> 13.2'
gem 'rspec', '~> 3.13'
gem 'selenium-webdriver', '~> 4.27'

group :development do
  gem 'bundler-audit', '~> 0.9'
end
