import java.util.Properties
import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import kotlinx.kover.gradle.plugin.dsl.GroupingEntityType

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlinx.kover")
}

val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) {
        file.inputStream().use { load(it) }
    }
}

val apiBaseUrl: String = localProperties.getProperty("api.base.url")
    ?: "http://10.0.2.2:8080/v1/"

private val testParallelForks: Int =
    (Runtime.getRuntime().availableProcessors() / 2).coerceIn(1, 4)

android {
    namespace = "com.example.demo"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.example.demo"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
    }

    androidResources {
        localeFilters += listOf("en", "es")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
        unitTests.all {
            if (it.name.contains("Release")) {
                it.enabled = false
            } else {
                it.maxParallelForks = testParallelForks
                it.exclude("**/pact/**")
            }
        }
    }
}

kover {
    reports {
        filters {
            excludes {
                androidGeneratedClasses()
                // Compiler-generated bytecode for @Composable () -> Unit lambdas and
                // ComposableSingletons — not the parent *ScreenKt / *Kt classes.
                classes(
                    "*ComposableSingletons*",
                    "*Kt$*"
                )
            }
        }
        variant("debug") {
            verify {
                rule {
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.LINE
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.INSTRUCTION
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.BRANCH
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                }
                rule {
                    groupBy = GroupingEntityType.CLASS
                    bound {
                        minValue = 100
                        coverageUnits = CoverageUnit.LINE
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                }
            }
        }
    }
}

afterEvaluate {
    tasks.named("testDebugUnitTest") {
        finalizedBy("koverVerifyDebug")
    }

    tasks.register<Test>("pactTest") {
        description = "Runs Pact consumer contract tests"
        group = "verification"

        val unitTest = tasks.named<Test>("testDebugUnitTest")
        dependsOn(
            "compileDebugUnitTestKotlin",
            "compileDebugUnitTestJavaWithJavac",
            "processDebugUnitTestJavaRes"
        )
        testClassesDirs = files(
            layout.buildDirectory.dir("tmp/kotlin-classes/debugUnitTest"),
            layout.buildDirectory.dir("intermediates/javac/debugUnitTest/compileDebugUnitTestJavaWithJavac/classes")
        )
        classpath = unitTest.get().classpath

        useJUnitPlatform()
        maxParallelForks = 1
        systemProperty(
            "pact.rootDir",
            layout.buildDirectory.dir("pacts").get().asFile.absolutePath
        )
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.1")
    val composeBom = platform("androidx.compose:compose-bom:2024.12.01")

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.navigation:navigation-compose:2.8.5")

    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")

    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-moshi:2.11.0")
    implementation("com.squareup.moshi:moshi-kotlin:1.15.2")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testImplementation("au.com.dius.pact.consumer:junit5:4.6.17")
    testImplementation("com.google.truth:truth:1.4.4")
    testImplementation("io.mockk:mockk:1.13.13")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
    testImplementation("androidx.arch.core:core-testing:2.2.0")
    testImplementation("org.robolectric:robolectric:4.14.1")
    testImplementation(composeBom)
    testImplementation("androidx.compose.ui:ui-test-junit4")
    testImplementation("androidx.compose.ui:ui")
    testImplementation("androidx.compose.material3:material3")
    testImplementation("androidx.compose.material:material-icons-extended")
    testImplementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    testImplementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    testImplementation("androidx.navigation:navigation-compose:2.8.5")
}
