import java.net.URI
import java.util.Properties
import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import kotlinx.kover.gradle.plugin.dsl.GroupingEntityType

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlinx.kover")
}

val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) {
        file.inputStream().use { load(it) }
    }
}

val apiBaseUrl: String = (findProperty("api.base.url") as String?)
    ?: localProperties.getProperty("api.base.url")
    ?: "http://10.0.2.2:8080/v1/"

fun wiremockHostFromApiBaseUrl(apiBaseUrl: String): String {
    val uri = URI(apiBaseUrl)
    val port = uri.port.takeIf { it != -1 }?.let { ":$it" } ?: ""
    return "${uri.scheme}://${uri.host}$port"
}

val wiremockUrl: String = (findProperty("wiremock.url") as String?)
    ?: localProperties.getProperty("wiremock.url")
    ?: wiremockHostFromApiBaseUrl(apiBaseUrl)

private val testParallelForks: Int =
    (Runtime.getRuntime().availableProcessors() / 2).coerceIn(1, 4)

private val allureKotlinVersion = "2.4.0"

android {
    namespace = "com.example.demo"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.example.demo"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
        buildConfigField("String", "WIREMOCK_URL", "\"$wiremockUrl\"")
        testInstrumentationRunner = "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"
        testInstrumentationRunnerArguments["clearPackageData"] = "true"
        testInstrumentationRunnerArguments["additionalTestOutputDir"] = "/sdcard/googletest/test_outputfiles"
    }

    androidResources {
        localeFilters += listOf("en", "es")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        animationsDisabled = true
        execution = "ANDROIDX_TEST_ORCHESTRATOR"
        unitTests.isIncludeAndroidResources = true
        unitTests.all {
            if (it.name.contains("Release")) {
                it.enabled = false
            } else {
                it.maxParallelForks = testParallelForks
                it.exclude("**/pact/**")
            }
        }
    }
}

kover {
    reports {
        filters {
            excludes {
                androidGeneratedClasses()
                // Compiler-generated bytecode for @Composable () -> Unit lambdas and
                // ComposableSingletons — not the parent *ScreenKt / *Kt classes.
                classes(
                    "*ComposableSingletons*",
                    "*Kt$*"
                )
            }
        }
        variant("debug") {
            verify {
                rule {
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.LINE
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.INSTRUCTION
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                    bound {
                        minValue = 90
                        coverageUnits = CoverageUnit.BRANCH
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                }
                rule {
                    groupBy = GroupingEntityType.CLASS
                    bound {
                        minValue = 100
                        coverageUnits = CoverageUnit.LINE
                        aggregationForGroup = AggregationType.COVERED_PERCENTAGE
                    }
                }
            }
        }
    }
}

afterEvaluate {
    tasks.named("testDebugUnitTest") {
        finalizedBy("koverVerifyDebug")
    }

    tasks.register<Test>("pactTest") {
        description = "Runs Pact consumer contract tests"
        group = "verification"

        val unitTest = tasks.named<Test>("testDebugUnitTest")
        dependsOn(
            "compileDebugUnitTestKotlin",
            "compileDebugUnitTestJavaWithJavac",
            "processDebugUnitTestJavaRes"
        )
        testClassesDirs = files(
            layout.buildDirectory.dir("tmp/kotlin-classes/debugUnitTest"),
            layout.buildDirectory.dir("intermediates/javac/debugUnitTest/compileDebugUnitTestJavaWithJavac/classes")
        )
        classpath = unitTest.get().classpath

        useJUnitPlatform()
        maxParallelForks = 1
        systemProperty(
            "pact.rootDir",
            layout.buildDirectory.dir("pacts").get().asFile.absolutePath
        )
    }

    tasks.matching { it.name.startsWith("connected") && it.name.endsWith("AndroidTest") }.configureEach {
        finalizedBy("pullAllureResults")
    }
}

configurations.configureEach {
    if (isCanBeResolved) {
        resolutionStrategy {
            activateDependencyLocking()
            force(
                "com.google.protobuf:protobuf-java:3.25.5",
                "com.google.protobuf:protobuf-javalite:3.25.5",
                "com.google.protobuf:protobuf-kotlin:3.25.5",
                "commons-beanutils:commons-beanutils:1.11.0",
                "org.apache.tika:tika-core:3.2.2",
                "org.bouncycastle:bcprov-jdk18on:1.84",
            )
            eachDependency {
                if (requested.group == "io.netty") {
                    useVersion("4.1.135.Final")
                    because("Fix GHSA netty vulnerabilities")
                }
            }
        }
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.1")
    val composeBom = platform("androidx.compose:compose-bom:2025.05.01")

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.navigation:navigation-compose:2.8.5")

    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3:1.4.0")
    implementation("androidx.compose.material:material-icons-extended")

    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-moshi:2.11.0")
    implementation("com.squareup.moshi:moshi-kotlin:1.15.2")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testImplementation("au.com.dius.pact.consumer:junit5:4.6.17")
    testImplementation("com.google.truth:truth:1.4.4")
    testImplementation("io.mockk:mockk:1.13.13")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
    testImplementation("androidx.arch.core:core-testing:2.2.0")
    testImplementation("org.robolectric:robolectric:4.14.1")
    testImplementation(composeBom)
    testImplementation("androidx.compose.ui:ui-test-junit4")
    testImplementation("androidx.compose.ui:ui")
    testImplementation("androidx.compose.material3:material3:1.4.0")
    testImplementation("androidx.compose.material:material-icons-extended")
    testImplementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    testImplementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    testImplementation("androidx.navigation:navigation-compose:2.8.5")

    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.test:runner:1.7.0")
    androidTestImplementation("androidx.test:rules:1.7.0")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.7.0")
    androidTestImplementation("com.google.truth:truth:1.4.4")
    androidTestImplementation("io.qameta.allure:allure-kotlin-model:$allureKotlinVersion")
    androidTestImplementation("io.qameta.allure:allure-kotlin-commons:$allureKotlinVersion")
    androidTestImplementation("io.qameta.allure:allure-kotlin-junit4:$allureKotlinVersion")
    androidTestImplementation("io.qameta.allure:allure-kotlin-android:$allureKotlinVersion")
    androidTestUtil("androidx.test:orchestrator:1.5.1")
    androidTestImplementation(composeBom)
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4-accessibility")
    androidTestImplementation("androidx.compose.material3:material3:1.4.0")
    androidTestDebugImplementation("androidx.compose.ui:ui-test-manifest")
}

val allureResultsDir = layout.buildDirectory.dir("allure-results")

tasks.register("pullAllureResults") {
    group = "verification"
    description = "Pull Allure results from the connected device or emulator"
    doLast {
        val outputDir = allureResultsDir.get().asFile
        outputDir.mkdirs()

        var pulledFromDevice = false
        exec {
            commandLine(
                "bash",
                "-c",
                """
                set +e
                adb exec-out sh -c 'cd /sdcard/googletest/test_outputfiles && tar cf - allure-results 2>/dev/null' \
                  | tar xf - --strip-components=1 -C "${outputDir.absolutePath}" 2>/dev/null
                if [ ! "$(ls -A "${outputDir.absolutePath}" 2>/dev/null)" ]; then
                  adb exec-out run-as com.example.demo sh -c 'cd files && tar cf - allure-results 2>/dev/null' \
                    | tar xf - --strip-components=1 -C "${outputDir.absolutePath}" 2>/dev/null
                fi
                """.trimIndent(),
            )
        }
        pulledFromDevice = outputDir.listFiles()?.any { it.name.endsWith("-result.json") } == true

        if (!pulledFromDevice) {
            val agpOutputRoot = layout.buildDirectory.dir("outputs/androidTest-results/connected").get().asFile
            if (agpOutputRoot.exists()) {
                agpOutputRoot.walkTopDown()
                    .filter { it.isDirectory && it.name == "allure-results" }
                    .forEach { source ->
                        source.listFiles()?.forEach { file ->
                            file.copyTo(outputDir.resolve(file.name), overwrite = true)
                        }
                    }
            }
        }

        exec {
            commandLine(
                "python3",
                "-c",
                """
                import json
                from pathlib import Path

                results_dir = Path("${outputDir.absolutePath}")
                by_history = {}
                for path in results_dir.glob("*-result.json"):
                    data = json.loads(path.read_text())
                    history_id = data.get("historyId") or path.name
                    step_count = len(data.get("steps") or [])
                    current = by_history.get(history_id)
                    if current is None or step_count > current[0]:
                        by_history[history_id] = (step_count, path)

                for history_id, (_, keep) in by_history.items():
                    for path in results_dir.glob("*-result.json"):
                        data = json.loads(path.read_text())
                        if (data.get("historyId") or path.name) == history_id and path != keep:
                            path.unlink(missing_ok=True)
                """.trimIndent(),
            )
        }
    }
}
