name: Android E2E tests

on:
  pull_request:
    branches: [master]
    paths:
      - 'demo-android/**'
      - 'demo-service/**'
      - 'docker/**'
      - '.github/workflows/android-e2e.yml'
      - '.github/workflows/android-compose-e2e.yml'
      - '.github/workflows/android-compose-accessibility.yml'
      - '.github/workflows/android-compose-uat.yml'
      - '.github/actions/**'
  push:
    branches: [master]
    paths:
      - 'demo-android/**'
      - 'demo-service/**'
      - 'docker/**'
      - '.github/workflows/android-e2e.yml'
      - '.github/workflows/android-compose-e2e.yml'
      - '.github/workflows/android-compose-accessibility.yml'
      - '.github/workflows/android-compose-uat.yml'
      - '.github/actions/**'

permissions:
  contents: read
  actions: read

jobs:
  android-compose-e2e:
    uses: ./.github/workflows/android-compose-e2e.yml
    secrets: inherit

  android-compose-accessibility:
    uses: ./.github/workflows/android-compose-accessibility.yml
    secrets: inherit

  android-compose-uat:
    uses: ./.github/workflows/android-compose-uat.yml
    secrets: inherit
