name: Run UAT tests (Cypress — full app)

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Start E2E environment
        uses: ./.github/actions/start-e2e-env
        with:
          app-mode: full
          docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run Cypress UAT tests
        uses: ./.github/actions/cypress-javascript-test
        with:
          npm-script: uat
          cypress-suite: uat
          split-count: '1'
          split-index: '0'
          app-mode: full
          test-label: Run Cypress UAT tests (full app)
          artifact-name: allure-results-cypress-uat
