name: Run e2e tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27018:27017

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: adopt
        cache: maven

    - name: build BE
      run: docker build -f docker/Dockerfile-demo-service --build-arg MONGODB_URL_ARG=mongodb://http://172.17.0.1:27018/demo_db -t docker-qa-demo-service .

    - name: build FE
      run: docker build -f docker/Dockerfile-demo-interface --build-arg BE_API_ARG=http://http://172.17.0.1:8080/v1 -t docker-qa-demo-interface .
    
    - name: run BE
      run: docker run -p 8080:8080 -d --name qa-demo-service docker-qa-demo-service

    - name: run FE
      run: docker run -p 3000:3000 -d --name qa-demo-interface docker-qa-demo-interface
    
    - name: Pull chrome image
      run: docker compose -f docker/docker-compose-run-selenoid.yml pull chrome

    - name: Start Selenoid
      run: docker compose -f docker/docker-compose-run-selenoid.yml up -d qa-demo-selenoid
       
    - name: Run e2e tests
      run: mvn -Dtest.env=remote -Dtest.tags=tmp test
    # - name: Create network
    #   run: docker network create qa-demo-network

    # - name: debug1
    #   run: docker ps -a

    # - name: Start application under test
    #   run: docker compose -f docker/docker-compose-run-application.yml up -d

    # - name: debug3
    #   run: sleep 10s && docker inspect qa-demo-mongo
    
    # - name: Pull chrome image
    #   run: docker compose -f docker/docker-compose-run-selenoid.yml pull chrome

    # - name: Start Selenoid
    #   run: docker compose -f docker/docker-compose-run-selenoid.yml up -d qa-demo-selenoid
      
    # - name: Run e2e tests
    #   run: mvn -Dtest.env=remote -Dtest.tags=tmp test
    
    # - name: debug4
    #   if: always()
    #   run: docker logs qa-demo-service

    # - name: Push allure report
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source-directory: 'selenide-selenoid-junit5-example/target/allure-results'
    #     destination-github-username: 'sgoldys'
    #     destination-repository-name: 'github-pages-allure-selenide'
    #     user-email: 32680292+sgoldys@users.noreply.github.com
    #     target-branch: gh-pages
    #     target-directory: allure-results
    
    # - name: Publish allure report
    #   run: gh workflow run allure-report.yml --ref master --repo sgoldys/github-pages-allure-selenide
    #   env:
    #     GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
