name: Run backend tests

on:
  push:
    branches:
      - '**'

jobs:
  unit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Run unit tests
        working-directory: demo-service
        run: mvn verify -DskipITs

  integration:
    runs-on: ubuntu-20.04
    needs: unit

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Run integration tests
        working-directory: demo-service
        run: mvn verify -Pintegration-tests -Dfailsafe.excludes='**/*PactProviderTest.java' -Djacoco.skip=true
