name: iOS E2E tests

on:
  pull_request:
    branches: [master]
    paths:
      - 'demo-ios/**'
      - 'demo-service/**'
      - 'docker/**'
      - '.github/workflows/ios-e2e.yml'
      - '.github/workflows/ios-xcuitest-e2e.yml'
      - '.github/workflows/ios-xcuitest-accessibility.yml'
      - '.github/workflows/ios-xcuitest-uat.yml'
      - '.github/actions/start-e2e-env/**'
  push:
    branches: [master]
    paths:
      - 'demo-ios/**'
      - 'demo-service/**'
      - 'docker/**'
      - '.github/workflows/ios-e2e.yml'
      - '.github/workflows/ios-xcuitest-e2e.yml'
      - '.github/workflows/ios-xcuitest-accessibility.yml'
      - '.github/workflows/ios-xcuitest-uat.yml'
      - '.github/actions/start-e2e-env/**'

permissions:
  contents: read
  actions: read

jobs:
  ios-xcuitest-e2e:
    uses: ./.github/workflows/ios-xcuitest-e2e.yml
    secrets: inherit

  ios-xcuitest-accessibility:
    uses: ./.github/workflows/ios-xcuitest-accessibility.yml
    secrets: inherit
